sync:
  local_root: "."
  remote_root: "~"
  files_to_sync: []

run:
  screen_session: "278347"
  env_setup: ""
  command: "echo '--- Start Screen Log Stream Test ---' && sleep 2 && echo 'Middle of test...' && sleep 2 && echo '--- Test Finished! ---'"
